apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "$name$.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "$name$.name" . }}
    helm.sh/chart: {{ include "$name$.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- range \$key, \$value := .Values.PublicEnvVars }}
  {{ \$key }}: {{ \$value | quote }}
{{- end }}
